[package]
name = "AoC-2020-day-03"
version = "0.1.0"
authors = ["Tiago Gomes <tacg@tacgomes.com>"]
edition = "2018"

[[bin]]
name = "03-part1"
path = "part1.rs"

[[bin]]
name = "03-part2"
path = "part2.rs"
