[package]
name = "AoC-2020-day-17"
version = "0.1.0"
authors = ["Tiago Gomes <tacg@tacgomes.com>"]
edition = "2018"

[[bin]]
name = "17-part1"
path = "part1.rs"

[[bin]]
name = "17-part2"
path = "part2.rs"
